Implement onboarding flow & integrate user profiles with server
MealsMadeEasy/Android pull request #26
Opened 2018-02-05 23:50 UTC by abailey96

Onboarding is now implemented and the profile page now accesses the server. Also, the app now properly handles configuration changes.

Edge cases & configuration changes handled (please test these if possible):
 - Logging into an account, and restarting the app without completing onboarding still takes the user to the onboarding page
 - Rotating the screen when editing the profile does not lose any data
 - Rotating the screen when saving the profile keeps the new activity in the same saving state

2018-02-06 02:19 UTC, adurso3 requested changes
Looks pretty good. I did check the edge cases you listed, and those are all behaving as expected.

2018-02-06 02:19 UTC, adurso3 commented on app/src/main/java/com/mealsmadeeasy/ui/home/profile/ProfileFragment.kt
> +        outState.putInt(KEY_SAVED_HEIGHT_FT, feetText.text.toString().toInt())
Not checking whether the text is actually convertible to an int will cause the app to crash when this method gets called on the initial onboarding screen.

2018-02-06 02:19 UTC, adurso3 commented on app/src/main/res/layout/view_user_profile.xml
> +                    android:textColor="#616161"
Should also probably be a resource.

2018-02-06 02:19 UTC, adurso3 commented on app/src/main/res/layout/view_user_profile.xml
> +                android:paddingEnd="16dp"
Resources please. ~~Revenge is sweet.~~

2018-02-06 18:44 UTC, abailey96 commented
Should be resolved now.

2018-02-07 00:51 UTC, adurso3 approved these changes

2018-02-07 00:51 UTC, merged